### ISSUE TITLE
Command not working.

### ISSUE THREAD

**Issue by ivenkatraj** [Harry260/WhatsApp-Plus#1] opened 2022-09-30 08:35 UTC
I installed the dependencies as per your cmd "npm install". I logged in to whatsapp using the qr. But i don't know which is not working. Whether the script or my command. I don't know how to create list or button in personal message. I am attaching both the screenshots in this issue.
![image](https://user-images.githubusercontent.com/64081780/193228369-87e37d6c-1b67-4195-b2a7-c8cb5a70cf3a.png)

![image](https://user-images.githubusercontent.com/64081780/193229254-019532ea-73df-4706-9646-858738959474.png)

![image](https://user-images.githubusercontent.com/64081780/193228623-da73cf28-bd9b-49c0-8eb7-6432e1e175bc.png)
Please resolve the issue.

**Comment by Harry260** [comment] 2022-09-30 13:15
@ivenkatraj  Thank you for addressing the issue. This was caused by your first message with no arguments, it is now fixed in the latest commit.

Now you can clone this again (or fetch) and do it again!

- Regards

**Closed as completed by Harry260** 2022-09-30 13:15 UTC
Labels: bug, good first issue
